title: New Tech Career
author: Cindy Baldhoff
email: cindy@cindybaldhoff.com
description: > # this means to ignore newlines until "baseurl:"
  This is an awesome way to learn coding. Having a background in journalism and editing, coding seems like a great segue for my skillset. 

# social links
twitter_username: fitnessgalcb
github_username:  fitnessgal

show_excerpts: true # set to false to remove excerpts on the homepage
